### ISSUE TITLE
clashofclans

### ISSUE THREAD

**Issue by kedsada** [Nilhcem/hosts-editor-android#18]
For me hacked or sever game app unlimited

**Comment by kedsada** [comment]
I want hack game clashofclans

**Comment by Nilhcem** [comment]
I want merge valid pullrequest

**Comment by faizaasan** [comment]
Faizaasan

**Comment by faizaasan** [comment]
l want hack game clashofclans

**Comment by kedsada** [comment]
How to hack gem clash of clans
