### ISSUE TITLE
Can't make new host

### ISSUE THREAD

**Issue by chaitnyasharma** [Nilhcem/hosts-editor-android#20]
When i add a new host than the error occur that you make sure you have root/super user rights.

**Comment by jokovic19** [comment]
I ask something regarding my host why not adding of host editor? Pls can I help me how to add.

**Comment by loshan44** [comment]
When i add a new host than the error occur that you make sure you have root/super user rights.

**Comment by Nilhcem** [comment]
Is your device rooted?

**Comment by pokemon244** [comment]
How do i get super user rights? Pls anyone help me

**Comment by yasirjaved** [comment]
How can I root my device ....

**Comment by Swank32** [comment]
How can I root my device
