### ISSUE TITLE
Request easy way to manage multiple domains pointing to the same IP address

### ISSUE THREAD

**Issue by coolplay** [Nilhcem/hosts-editor-android#7]
As always, I need to change the IP address for Google domains. For now, I need to manually change every IP address for each Google host, and I am just wondering if there'll be an quick way to modify the same IP with a single step.

**Comment by nurazmi** [comment]
119.81.3.196

**Comment by qwertyuiopasdfghjklzxcvnm** [comment]
Oooooo

**Comment by zainihajar66** [comment]
Yes

**Comment by yegyi** [comment]
Aungye

**Comment by yegyi** [comment]
Aungye

**Comment by yegyi** [comment]
yegyi

**Comment by yegyi** [comment]
wilwilfl123@gmail.com

**Comment by okku1** [comment]
Ip

**Comment by JavoxirSobirov** [comment]
79.122.186.54

**Comment by sazzuwe** [comment]
fhsghyctub vc

**Comment by sazzuwe** [comment]
ctxexyguv uvuv

**Comment by sazzuwe** [comment]
ycrxyuvu

**Comment by eliasmorales247** [comment]
help me please i dont get it
